export const MOCK_ACCEPTANCE_REQUESTS = [
  {
    id: 1,
    employeeName: 'NguyenVanA_Tech',
    deviceCode: 'TB-9981',
    deviceName: 'Máy nén khí Piston',
    errorDescription: 'Máy không lên nguồn, tụ điện bị cháy hỏng do quá tải.',
    solution: 'Thay mới tụ điện 450V và vệ sinh toàn bộ khoang máy.',
    usedComponents: '1x Tụ điện CBB65 45uF, 2m Dây điện chịu nhiệt',
    userConfirmation: true,
    createdAt: '09:15 30/03/2026',
    estimatedCost: 850000,
    managerName: 'TranQuanLy_01',
    status: 'PENDING',
    evaluation: '',
    rejectReason: ''
  },
  {
    id: 2,
    employeeName: 'LeVanB_Fixer',
    deviceCode: 'PG-002',
    deviceName: 'Máy phát điện Cummins',
    errorDescription: 'Rò rỉ dầu động cơ và quạt tản nhiệt kêu to bất thường.',
    solution: 'Thay gioăng phớt chắn dầu và tra mỡ bôi trơn ổ bi quạt.',
    usedComponents: '1x Phớt dầu Cummins, 1x Hộp mỡ bôi trơn',
    userConfirmation: false,
    createdAt: '14:30 29/03/2026',
    estimatedCost: 1200000,
    managerName: 'TranQuanLy_01',
    status: 'PENDING',
    evaluation: '',
    rejectReason: ''
  },
  {
    id: 3,
    employeeName: 'PhamThanhC_Maint',
    deviceCode: 'CNC-104',
    deviceName: 'Máy phay CNC 3 trục',
    errorDescription: 'Lỗi định vị trục Z khi chạy chương trình cắt tải nặng.',
    solution: 'Căn chỉnh lại thước đo tuyến tính và căn lại độ rơ vít me.',
    usedComponents: 'Không dùng linh kiện thay thế',
    userConfirmation: true,
    createdAt: '08:00 28/03/2026',
    estimatedCost: 450000,
    managerName: 'TranQuanLy_01',
    status: 'APPROVED',
    evaluation: 'Xử lý nhanh, máy chạy êm và đạt độ chính xác yêu cầu.',
    rejectReason: ''
  },
  {
    id: 4,
    employeeName: 'HoangVanD_Tech',
    deviceCode: 'PL-088',
    deviceName: 'Xe nâng điện Toyota 2.5T',
    errorDescription: 'Hệ thống thủy lực nâng hạ bị yếu, bình ắc quy sụt áp nhanh.',
    solution: 'Thay bộ van tiết lưu thủy lực và châm thêm dung dịch ắc quy.',
    usedComponents: '1x Bộ van tiết lưu Toyota, 5L Dung dịch axit phốt',
    userConfirmation: false,
    createdAt: '16:45 27/03/2026',
    estimatedCost: 3500000,
    managerName: 'TranQuanLy_02',
    status: 'REJECTED',
    evaluation: '',
    rejectReason: 'Chi phí linh kiện vượt định mức cho phép, cần giải trình rõ nguồn gốc linh kiện.'
  },
  {
    id: 5,
    employeeName: 'DoanThiE_IT',
    deviceCode: 'SRV-01',
    deviceName: 'Máy chủ Dell PowerEdge R740',
    errorDescription: 'Ổ cứng số 3 trong mảng RAID 5 bị báo cờ đỏ (Degraded).',
    solution: 'Rút nóng ổ cứng hỏng, thay ổ SAS mới và rebuild lại RAID.',
    usedComponents: '1x Ổ cứng Dell SAS 1.2TB 10k RPM',
    userConfirmation: true,
    createdAt: '11:20 26/03/2026',
    estimatedCost: 4200000,
    managerName: 'TranQuanLy_01',
    status: 'APPROVED',
    evaluation: 'Hoàn thành đúng quy trình bảo mật và khôi phục dữ liệu an toàn.',
    rejectReason: ''
  },
  {
    id: 6,
    employeeName: 'NguyenVanA_Tech',
    deviceCode: 'AC-302',
    deviceName: 'Điều hòa trung tâm Daikin',
    errorDescription: 'Block máy lạnh không chạy, quạt dàn nóng thổi ra gió nóng.',
    solution: 'Bơm bổ sung gas R410A và thay khởi động từ (Contactor).',
    usedComponents: '2kg Gas R410A, 1x Contactor Daikin 30A',
    userConfirmation: true,
    createdAt: '10:00 25/03/2026',
    estimatedCost: 1600000,
    managerName: 'TranQuanLy_02',
    status: 'PENDING',
    evaluation: '',
    rejectReason: ''
  },
  {
    id: 7,
    employeeName: 'VuHoangF_Tech',
    deviceCode: 'PUMP-05',
    deviceName: 'Máy bơm nước ly tâm Ebara',
    errorDescription: 'Hỏng phớt cơ khí gây chảy nước ra văng trục động cơ.',
    solution: 'Tháo dỡ buồng bơm, thay phớt mặt chai và ép lại vòng bi.',
    usedComponents: '1x Bộ phớt cơ khí Ebara Ø28, 2x Vòng bi SKF 6205',
    userConfirmation: false,
    createdAt: '13:10 24/03/2026',
    estimatedCost: 950000,
    managerName: 'TranQuanLy_01',
    status: 'PENDING',
    evaluation: '',
    rejectReason: ''
  },
  {
    id: 8,
    employeeName: 'LeVanB_Fixer',
    deviceCode: 'CUT-12',
    deviceName: 'Máy cắt Laser Fiber 1000W',
    errorDescription: 'Thấu kính hội tụ bị bám bẩn và xước nhẹ bề mặt.',
    solution: 'Vệ sinh dung dịch chuyên dụng và cân chỉnh điểm tiêu cự tia.',
    usedComponents: '1x Bộ giấy lau quang học + Cồn 99 độ',
    userConfirmation: true,
    createdAt: '15:40 23/03/2026',
    estimatedCost: 300000,
    managerName: 'TranQuanLy_01',
    status: 'APPROVED',
    evaluation: 'Đường cắt phẳng đẹp, không còn bavia.',
    rejectReason: ''
  },
  {
    id: 9,
    employeeName: 'PhamThanhC_Maint',
    deviceCode: 'COMP-03',
    deviceName: 'Máy nén khí Trục vít Hitachi',
    errorDescription: 'Nhiệt độ đầu nén quá cao (>105 độ C) gây ngắt tự động.',
    solution: 'Thay bộ lọc dầu, lọc tách dầu và tẩy rửa két tản nhiệt.',
    usedComponents: '1x Lọc dầu Hitachi, 1x Lọc tách nhớt, 20L Nhớt máy nén',
    userConfirmation: true,
    createdAt: '09:00 22/03/2026',
    estimatedCost: 6800000,
    managerName: 'TranQuanLy_02',
    status: 'APPROVED',
    evaluation: 'Nhiệt độ vận hành đã hạ về mức an toàn 82 độ C.',
    rejectReason: ''
  },
  {
    id: 10,
    employeeName: 'HoangVanD_Tech',
    deviceCode: 'CV-101',
    deviceName: 'Băng tải con lăn phân loại',
    errorDescription: 'Động cơ giảm tốc bị trượt xích, phát ra tiếng động rít.',
    solution: 'Tăng xích truyền động và thay mới 2 con lăn bị cong vênh.',
    usedComponents: '2x Con lăn mạ kẽm Ø60x500mm',
    userConfirmation: false,
    createdAt: '17:15 21/03/2026',
    estimatedCost: 750000,
    managerName: 'TranQuanLy_01',
    status: 'REJECTED',
    evaluation: '',
    rejectReason: 'Chưa có chữ ký xác nhận nghiệm thu chạy thử của quản lý ca sản xuất.'
  },
  {
    id: 11,
    employeeName: 'NguyenVanA_Tech',
    deviceCode: 'WELD-08',
    deviceName: 'Máy hàn TIG Panasonic',
    errorDescription: 'Súng hàn bị chập dây điều khiển, không ngắt được khí.',
    solution: 'Sửa lại dây công tắc tay hàn và thay béc phun khí khói.',
    usedComponents: '1x Bộ mỏ hàn TIG WP26, 5x Béc sứ #6',
    userConfirmation: true,
    createdAt: '08:30 20/03/2026',
    estimatedCost: 550000,
    managerName: 'TranQuanLy_01',
    status: 'PENDING',
    evaluation: '',
    rejectReason: ''
  },
  {
    id: 12,
    employeeName: 'VuHoangF_Tech',
    deviceCode: 'SCALE-01',
    deviceName: 'Cân điện tử sàn 3 Tấn',
    errorDescription: 'Cân nhảy số liên tục, sai lệch trọng lượng lớn.',
    solution: 'Thay cảm biến lực Loadcell góc trái và hiệu chuẩn lại chuẩn F1.',
    usedComponents: '1x Cảm biến Loadcell Keli 1.5T',
    userConfirmation: true,
    createdAt: '14:00 19/03/2026',
    estimatedCost: 2100000,
    managerName: 'TranQuanLy_02',
    status: 'APPROVED',
    evaluation: 'Đã có tem dán kiểm định đạt chuẩn.',
    rejectReason: ''
  },
  {
    id: 13,
    employeeName: 'LeVanB_Fixer',
    deviceCode: 'PRESS-04',
    deviceName: 'Máy dập thủy lực 100 Tấn',
    errorDescription: 'Hệ thống van điện từ bị kẹt cuộn coi làm hành trình dập chậm.',
    solution: 'Vệ sinh solenoid valve và thay cuộn coil 24VDC mới.',
    usedComponents: '1x Cuộn Coil Yuken 24VDC',
    userConfirmation: false,
    createdAt: '10:45 18/03/2026',
    estimatedCost: 1350000,
    managerName: 'TranQuanLy_01',
    status: 'PENDING',
    evaluation: '',
    rejectReason: ''
  },
  {
    id: 14,
    employeeName: 'DoanThiE_IT',
    deviceCode: 'PRN-09',
    deviceName: 'Máy in mã vạch Zebra ZT411',
    errorDescription: 'Đầu in bị đứt nét (xước dải nhiệt) in ra bị mờ thanh vạch.',
    solution: 'Thay đầu in nhiệt mới chính hãng Zebra 203dpi.',
    usedComponents: '1x Đầu in Zebra ZT411 203dpi',
    userConfirmation: true,
    createdAt: '16:00 17/03/2026',
    estimatedCost: 5200000,
    managerName: 'TranQuanLy_01',
    status: 'APPROVED',
    evaluation: 'Mã vạch in ra sắc nét, máy quét đọc mượt.',
    rejectReason: ''
  },
  {
    id: 15,
    employeeName: 'PhamThanhC_Maint',
    deviceCode: 'INVT-02',
    deviceName: 'Biến tần Yaskawa 15kW',
    errorDescription: 'Báo lỗi OC (Overcurrent) ngay khi ấn lệnh Start.',
    solution: 'Thay bo mạch công suất IGBT và kiểm tra lại cách điện động cơ.',
    usedComponents: '1x Module IGBT Fuji 75A',
    userConfirmation: false,
    createdAt: '09:30 16/03/2026',
    estimatedCost: 3800000,
    managerName: 'TranQuanLy_02',
    status: 'REJECTED',
    evaluation: '',
    rejectReason: 'Thời gian bảo hành linh kiện thay thế chưa đủ 6 tháng theo cam kết.'
  }
];