// =========================================================
// 1. MOCK DATA THIẾT BỊ ĐIỆN THOẠI & MÁY TÍNH BẢNG (MÃ: TB-DT-xxx)
// =========================================================
export const MOCK_PHONE_DEVICES = [
  {
    id: 'TB-DT-001',
    deviceId: 'TB-DT-001',
    deviceName: 'iPhone 15 Pro Max 256GB',
    category: 'Điện thoại GD',
    serialNumber: '354928110293841',
    specifications: 'Apple A17 Pro, 8GB RAM, Type-C, Titanium',
    department: 'Ban Giám Đốc',
    assignedTo: 'Nguyễn Văn An (CEO)',
    status: 'Đang sử dụng', // 'Đang sử dụng' | 'Chờ xử lý' | 'Đang sửa chữa' | 'Kho dự phòng'
    priority: 'HIGH',       // 'HIGH' | 'NORMAL'
    installedDate: '2026-08-12',
    price: 32990000,
    warrantyMonths: 12,
    location: 'Phòng Giám Đốc - Tầng 4',
    notes: 'Cấp mới theo tiêu chuẩn GD'
  },
  {
    id: 'TB-DT-002',
    deviceId: 'TB-DT-002',
    deviceName: 'iPhone 14 Pro 128GB',
    category: 'Điện thoại GD',
    serialNumber: '358123091823741',
    specifications: 'Apple A16 Bionic, 6GB RAM, Space Black',
    department: 'Ban Giám Đốc',
    assignedTo: 'Trần Thị Bích (CFO)',
    status: 'Đang sử dụng',
    priority: 'NORMAL',
    installedDate: '2026-08-10',
    price: 24500000,
    warrantyMonths: 12,
    location: 'Phòng Phó Giám Đốc - Tầng 4',
    notes: 'Giao máy kèm bao da chống va đập'
  },
  {
    id: 'TB-DT-003',
    deviceId: 'TB-DT-003',
    deviceName: 'Samsung Galaxy S24 Ultra',
    category: 'Smartphone',
    serialNumber: '359812304912832',
    specifications: 'Snapdragon 8 Gen 3, 12GB RAM, 256GB, S-Pen',
    department: 'Phòng Kinh Doanh',
    assignedTo: 'Lê Hoàng Nam (TP KD)',
    status: 'Chờ xử lý',
    priority: 'HIGH',
    installedDate: '2026-08-09',
    price: 29990000,
    warrantyMonths: 12,
    location: 'Phòng Kinh Doanh - Tầng 2',
    notes: 'Báo lỗi không kết nối được WiFi công ty'
  },
  {
    id: 'TB-DT-004',
    deviceId: 'TB-DT-004',
    deviceName: 'Samsung Galaxy A54 5G',
    category: 'Smartphone',
    serialNumber: '352341092831204',
    specifications: 'Exynos 1380, 8GB RAM, 128GB',
    department: 'Phòng CSKH',
    assignedTo: 'Phạm Thị Mai',
    status: 'Đang sử dụng',
    priority: 'NORMAL',
    installedDate: '2026-08-12',
    price: 8490000,
    warrantyMonths: 12,
    location: 'Phòng CSKH - Tầng 1',
    notes: 'Dùng nghe gọi hotline CSKH 1'
  },
  {
    id: 'TB-DT-005',
    deviceId: 'TB-DT-005',
    deviceName: 'Xiaomi Redmi Note 13',
    category: 'Smartphone Test',
    serialNumber: '864239012830192',
    specifications: 'Snapdragon 685, 6GB RAM, 128GB',
    department: 'Phòng IT',
    assignedTo: 'Đỗ Mạnh Hùng',
    status: 'Kho dự phòng',
    priority: 'NORMAL',
    installedDate: '2026-03-01',
    price: 4690000,
    warrantyMonths: 12,
    location: 'Phòng Server IT - Tầng 3',
    notes: 'Máy test ứng dụng Mobile cho KT'
  },
  {
    id: 'TB-DT-006',
    deviceId: 'TB-DT-006',
    deviceName: 'iPad Pro 11 inch M2 (2026)',
    category: 'Máy tính bảng',
    serialNumber: 'DMPX9201KD92',
    specifications: 'Apple M2, 128GB, Wi-Fi + 5G, Apple Pencil 2',
    department: 'Phòng Thiết Kế',
    assignedTo: 'Nguyễn Thùy Linh',
    status: 'Đang sửa chữa',
    priority: 'HIGH',
    installedDate: '2026-08-13',
    price: 21990000,
    warrantyMonths: 12,
    location: 'Trung tâm BH Apple Care',
    notes: 'Đang thay mặt kính màn hình do va đập'
  },
  {
    id: 'TB-DT-007',
    deviceId: 'TB-DT-007',
    deviceName: 'Grandstream GRP2601P',
    category: 'Điện thoại bàn IP',
    serialNumber: '230918239012',
    specifications: 'PoE, 2 SIP Accounts, LCD Display, HD Audio',
    department: 'Lễ Tân',
    assignedTo: 'Lễ Tân Tầng 1',
    status: 'Đang sử dụng',
    priority: 'NORMAL',
    installedDate: '2026-06-10',
    price: 1250000,
    warrantyMonths: 24,
    location: 'Sảnh Lễ Tân - Tầng 1',
    notes: 'Điện thoại bàn nghe gọi tổng đài chính'
  }
];

// =========================================================
// 2. MOCK DATA THIẾT BỊ VĂN PHÒNG (MÃ: TB-VP-xxx)
// =========================================================
export const MOCK_OFFICE_DEVICES = [
  {
    id: 'TB-VP-001',
    deviceId: 'TB-VP-001',
    deviceName: 'Máy in Canon MF244dw',
    category: 'Máy in đa năng',
    serialNumber: 'CN20269102',
    specifications: 'In 2 mặt tự động, Scan, Copy, WiFi, 27 trang/phút',
    department: 'Phòng Hành Chính',
    assignedTo: 'Trần Thị Hoa',
    status: 'Chờ xử lý',
    priority: 'HIGH',
    installedDate: '2026-04-12',
    price: 6850000,
    warrantyMonths: 12,
    location: 'Phòng Hành Chính - Tầng 2',
    notes: 'Báo lỗi kẹt giấy khay tự động đảo chiều'
  },
  {
    id: 'TB-VP-002',
    deviceId: 'TB-VP-002',
    deviceName: 'Máy in HP LaserJet M404dn',
    category: 'Máy in Laser',
    serialNumber: 'VNC3K02918',
    specifications: 'In Laser đen trắng, Đảo mặt, Cổng Mạng LAN',
    department: 'Phòng Kế Toán',
    assignedTo: 'Lê Thị Thu',
    status: 'Đang sử dụng',
    priority: 'NORMAL',
    installedDate: '2026-01-18',
    price: 7200000,
    warrantyMonths: 12,
    location: 'Phòng Kế Toán - Tầng 2',
    notes: 'Chuyên dùng in hóa đơn & chứng từ'
  },
  {
    id: 'TB-VP-003',
    deviceId: 'TB-VP-003',
    deviceName: 'Máy Photocopy Ricoh MP 5055SP',
    category: 'Máy Photocopy',
    serialNumber: 'W9281029301',
    specifications: 'Khổ A3/A4, In mạng, Scan màu, Speed 50 cpm',
    department: 'Dùng chung',
    assignedTo: 'Phòng HCNS Quản Lý',
    status: 'Chưa phân công',
    priority: 'HIGH',
    installedDate: '2026-11-05',
    price: 45000000,
    warrantyMonths: 36,
    location: 'Hành Lang Trung Tâm - Tầng 2',
    notes: 'Cần thay cụm trống (Drum) và gạt mực định kỳ'
  },
  {
    id: 'TB-VP-004',
    deviceId: 'TB-VP-004',
    deviceName: 'Máy Scan Fujitsu iX1600',
    category: 'Máy Scan siêu tốc',
    serialNumber: 'B9201928301',
    specifications: 'Scan 2 mặt tự động, 40 tờ/phút, Màn hình cảm ứng 4.3 inch',
    department: 'Phòng Hồ Sơ',
    assignedTo: 'Phạm Quốc Anh',
    status: 'Đang sử dụng',
    priority: 'NORMAL',
    installedDate: '2026-06-22',
    price: 11800000,
    warrantyMonths: 12,
    location: 'Phòng Lưu Trữ - Tầng 1',
    notes: 'Số hóa tài liệu văn bản công ty'
  },
  {
    id: 'TB-VP-005',
    deviceId: 'TB-VP-005',
    deviceName: 'Máy chiếu Epson EB-FH52',
    category: 'Máy chiếu',
    serialNumber: 'X9201923812',
    specifications: 'Full HD 1080p, 4.000 Ansi Lumens, WiFi tích hợp',
    department: 'Phòng Họp',
    assignedTo: 'Đỗ Mạnh Hùng (IT)',
    status: 'Chờ xử lý',
    priority: 'NORMAL',
    installedDate: '2026-09-10',
    price: 18500000,
    warrantyMonths: 24,
    location: 'Phòng Họp Lớn - Tầng 3',
    notes: 'Bóng đèn mờ, báo lỗi quá nhiệt (Overheat)'
  },
  {
    id: 'TB-VP-006',
    deviceId: 'TB-VP-006',
    deviceName: 'Máy chấm công Ronald Jack RJ3800',
    category: 'Máy chấm công',
    serialNumber: 'RJ202610293',
    specifications: 'Chấm công Vân tay + Nhận diện khuôn mặt FaceID',
    department: 'Phòng Nhân Sự',
    assignedTo: 'Hoàng Kim Oanh',
    status: 'Đang sử dụng',
    priority: 'HIGH',
    installedDate: '2026-01-08',
    price: 3500000,
    warrantyMonths: 12,
    location: 'Sảnh Lễ Tân - Tầng 1',
    notes: 'Kết nối mạng LAN nội bộ gửi dữ liệu ca làm'
  },
  {
    id: 'TB-VP-007',
    deviceId: 'TB-VP-007',
    deviceName: 'Máy hủy tài liệu Silicon PS-800C',
    category: 'Máy hủy tài liệu',
    serialNumber: 'SL829102938',
    specifications: 'Hủy siêu vụn, Dung tích 21L, Bảo mật Level P-4',
    department: 'Ban Giám Đốc',
    assignedTo: 'Nguyễn Văn An',
    status: 'Đang sử dụng',
    priority: 'NORMAL',
    installedDate: '2026-03-14',
    price: 4200000,
    warrantyMonths: 12,
    location: 'Phòng Giám Đốc - Tầng 4',
    notes: 'Dùng hủy tài liệu bảo mật nội bộ'
  },
  {
    id: 'TB-VP-008',
    deviceId: 'TB-VP-008',
    deviceName: 'Máy đếm tiền Xinda Super BC-35',
    category: 'Máy đếm tiền',
    serialNumber: 'XD920192831',
    specifications: 'Đếm phát hiện tiền giả, Tiền lẫn loại, Băng tải dài',
    department: 'Phòng Kế Toán',
    assignedTo: 'Lê Thị Thu',
    status: 'Đang sửa chữa',
    priority: 'HIGH',
    installedDate: '2026-05-20',
    price: 6900000,
    warrantyMonths: 12,
    location: 'Trung Tâm Bảo Hành Xinda',
    notes: 'Đang thay mắt đọc kiểm tra tiền giả'
  }
];

// =========================================================
// 3. TỔNG HỢP TOÀN BỘ DANH SÁCH THIẾT BỊ (ALL IN ONE)
// =========================================================
export const MOCK_ALL_DEVICES = [
  ...MOCK_PHONE_DEVICES,
  ...MOCK_OFFICE_DEVICES
];