// Cấu hình danh mục loại yêu cầu người dùng thiết bị điện tử văn phòng
export const USER_REQUEST_TYPES = {
  REPORT_BROKEN: { label: 'Báo hỏng', badgeClass: 'type-broken' },
  REQUEST_EQUIPMENT: { label: 'Yêu cầu cấp thiết bị', badgeClass: 'type-provide' },
  RETURN_EQUIPMENT: { label: 'Yêu cầu trả thiết bị', badgeClass: 'type-return' },
  RESCHEDULE_MAINTENANCE: { label: 'Yêu cầu dời lịch bảo trì thiết bị', badgeClass: 'type-reschedule' }
};

// Dữ liệu giả lập 16 bản ghi thiết bị điện tử văn phòng
export const MOCK_USER_REQUESTS = [
  {
    id: 1,
    type: 'REPORT_BROKEN',
    priority: 'URGENT',
    deviceCode: 'PRN-HP-404',
    employeeName: 'Nguyễn Văn An',
    content: 'Máy in phòng Kế toán bị kẹt giấy liên tục, có tiếng lạch cạch lớn khi cuốn giấy và in ra bị vệt đen dọc trang.',
    createdAt: '2026-03-30T09:15:00',
    estimatedCost: 850000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 2,
    type: 'REQUEST_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'LAP-DELL-5520',
    employeeName: 'Lê Thị Bình',
    content: 'Yêu cầu cấp 01 Laptop Dell Latitude phòng Nhân sự phục vụ nhân viên mới thử việc đợt tháng 4.',
    createdAt: '2026-03-30T08:30:00',
    estimatedCost: 16500000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 3,
    type: 'RETURN_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'PROJECTOR-EPSON-01',
    employeeName: 'Trần Hoàng Nam',
    content: 'Hoàn trả máy chiếu di động Epson phòng họp nhỏ do dự án đào tạo nội bộ đã kết thúc.',
    createdAt: '2026-03-29T14:20:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'ACCEPTED',
    rejectReason: ''
  },
  {
    id: 4,
    type: 'RESCHEDULE_MAINTENANCE',
    priority: 'NORMAL',
    deviceCode: 'LAP-THINKPAD-T14',
    employeeName: 'Nguyễn Thị Mai',
    content: 'Xin dời lịch bảo trì, vệ sinh và tra keo tản nhiệt Laptop ThinkPad sang tuần sau do đang bận chạy tiến độ dự án.',
    createdAt: '2026-03-28T11:00:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'REJECTED',
    rejectReason: 'Không thể dời lịch quá xa vì máy đã quá thời hạn bảo trì định kỳ 6 tháng, dễ gây quá nhiệt cháy mainboard.'
  },
  {
    id: 5,
    type: 'REPORT_BROKEN',
    priority: 'URGENT',
    deviceCode: 'SCANNER-FUJITSU-02',
    employeeName: 'Phạm Minh Đức',
    content: 'Máy Scan tài liệu phòng Pháp chế bị mất nguồn đột ngột, cắm lại dây nguồn vẫn không sáng đèn báo.',
    createdAt: '2026-03-28T10:45:00',
    estimatedCost: 1200000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 6,
    type: 'REQUEST_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'MON-DELL-27',
    employeeName: 'Phan Hoàng Phúc',
    content: 'Đề xuất cấp thêm 01 Màn hình đồ họa Dell UltraSharp 27 inch cho vị trí Thiết kế Marketing.',
    createdAt: '2026-03-27T15:30:00',
    estimatedCost: 8200000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 7,
    type: 'RETURN_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'SW-TP-8P',
    employeeName: 'Bùi Thị Phương',
    content: 'Bàn giao lại Bộ chia mạng Switch TP-Link 8 port dư thừa sau khi hoàn thành tái cấu trúc mạng phòng Marketing.',
    createdAt: '2026-03-27T09:10:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'ACCEPTED',
    rejectReason: ''
  },
  {
    id: 8,
    type: 'RESCHEDULE_MAINTENANCE',
    priority: 'NORMAL',
    deviceCode: 'LAP-MACBOOK-PRO14',
    employeeName: 'Đỗ Văn Giang',
    content: 'Xin hoãn lịch kiểm tra và thay pin Laptop Macbook Pro sang chiều thứ 6 để hoàn thành in ấn hồ sơ thầu.',
    createdAt: '2026-03-26T16:20:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'ACCEPTED',
    rejectReason: ''
  },
  {
    id: 9,
    type: 'REPORT_BROKEN',
    priority: 'URGENT',
    deviceCode: 'ATTENDANCE-RJ-01',
    employeeName: 'Vũ Thị Hoa',
    content: 'Máy chấm công khuôn mặt cổng chính bị treo màn hình cảm ứng, không nhận diện được nhân viên ca sáng.',
    createdAt: '2026-03-26T07:45:00',
    estimatedCost: 1500000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 10,
    type: 'REQUEST_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'CAM-LOGI-C920',
    employeeName: 'Trịnh Văn Hải',
    content: 'Đề xuất trang bị 01 Webcam Logitech Full HD và Micro thu âm phục vụ các buổi họp trực tuyến với đối tác.',
    createdAt: '2026-03-25T14:10:00',
    estimatedCost: 2100000,
    managerName: 'Trần Quản Lý',
    status: 'REJECTED',
    rejectReason: 'Phòng họp đã trang bị sẵn hệ thống Meeting Bar chuyên dụng, không mua lẻ Webcam cho cá nhân.'
  },
  {
    id: 11,
    type: 'RETURN_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'PC-HP-PRO-03',
    employeeName: 'Nguyễn Thị Kim Khánh',
    content: 'Trả lại bộ máy tính để bàn HP ProDesk cũ sau khi đã nhận bàn giao máy tính xách tay làm việc mới.',
    createdAt: '2026-03-25T11:00:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'ACCEPTED',
    rejectReason: ''
  },
  {
    id: 12,
    type: 'REPORT_BROKEN',
    priority: 'NORMAL',
    deviceCode: 'MIC-SHURE-VP',
    employeeName: 'Mai Văn Long',
    content: 'Micro không dây phòng hội thảo tổng công ty bị chập chờn tín hiệu, xuất hiện tiếng hú dải tần cao.',
    createdAt: '2026-03-24T13:40:00',
    estimatedCost: 600000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 13,
    type: 'RESCHEDULE_MAINTENANCE',
    priority: 'NORMAL',
    deviceCode: 'LAP-DELL-XPS13',
    employeeName: 'Đinh Thị Mỹ',
    content: 'Yêu cầu đổi giờ kiểm tra phần mềm và nâng cấp SSD cho Laptop Dell XPS sang ngoài giờ hành chính để tránh ảnh hưởng công việc.',
    createdAt: '2026-03-24T09:30:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'ACCEPTED',
    rejectReason: ''
  },
  {
    id: 14,
    type: 'REQUEST_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'PRN-CANON-2900',
    employeeName: 'Cao Văn Nam',
    content: 'Yêu cầu cấp 01 máy in đơn năng Canon 2900 cho bộ phận Kho để in phiếu xuất kho nhanh.',
    createdAt: '2026-03-23T15:00:00',
    estimatedCost: 3950000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 15,
    type: 'REPORT_BROKEN',
    priority: 'NORMAL',
    deviceCode: 'SHREDDER-SILICON-01',
    employeeName: 'Dương Thị Phương',
    content: 'Máy hủy tài liệu phòng Trợ lý HĐQT bị kẹt lưỡi cắt kim loại, cắm điện có tiếng rơ-le ngắt liên tục.',
    createdAt: '2026-03-23T10:15:00',
    estimatedCost: 750000,
    managerName: 'Trần Quản Lý',
    status: 'PENDING',
    rejectReason: ''
  },
  {
    id: 16,
    type: 'RETURN_EQUIPMENT',
    priority: 'NORMAL',
    deviceCode: 'PAD-DRAW-XP',
    employeeName: 'Lư Anh Quân',
    content: 'Trả Bảng vẽ điện tử XP-Pen do nhân viên thiết kế cũ nghỉ việc, đã kiểm tra đầy đủ phụ kiện bút vẽ.',
    createdAt: '2026-03-22T16:30:00',
    estimatedCost: 0,
    managerName: 'Trần Quản Lý',
    status: 'ACCEPTED',
    rejectReason: ''
  }
];